### ISSUE TITLE
Translation for tourists

### ISSUE THREAD

**Issue by nlsn** [dslul/ticketreader#2]
This is a very useful little app. *Grazie!*

I would like to help make an English interface available, which I think would be useful to a variety of tourists using the metro.

I was thinking of translating these strings: https://github.com/dslul/ticketreader/blob/master/app/src/main/res/values/strings.xml

But how should the option be made for Italiano vs. other languages? I'm not familiar with app development.

Thanks!

**Comment by dslul** [comment]
Hi, I took some time to add support for translation. To add languages, it is sufficient to add a folder with the strings to translate in it, like this: https://github.com/dslul/ticketreader/tree/master/app/src/main/res/values-it. However, with Android Studio this can be done with a GUI. If you want, you can translate the file you linked, it is the default one, I guess it's better to be English rather than Italian.

Thank you

**Comment by nlsn** [comment]
It seems GTT uses "trips" in their English translation: http://www.gtt.to.it/cms/en/fares

My suggestion is to maintain consistency with GTT.

**Comment by nlsn** [comment]
I update the branch on my fork.

**Comment by dslul** [comment]
Great, thank you!
Can you create a pull request with your commit, so I can merge into the main branch?

**Comment by dslul** [comment]
Merged and updated on the Play Store. If you confirm, I can close this issue.

**Comment by nlsn** [comment]
I don't have a metro ticket with me right now, but the text I can see without scanning is English now.
